// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYW_wi_nJWpt_4CiBbHASbx0dAF0hxnms',
    appId: '1:47237302350:web:779a74b190c0851bc71b1f',
    messagingSenderId: '47237302350',
    projectId: 'insync-class',
    authDomain: 'insync-class.firebaseapp.com',
    storageBucket: 'insync-class.appspot.com',
    measurementId: 'G-CSRV098B8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0plZjMo6c-cQYszLVLH0NiKJmbFkQ48U',
    appId: '1:47237302350:android:ea5ba8231544323cc71b1f',
    messagingSenderId: '47237302350',
    projectId: 'insync-class',
    storageBucket: 'insync-class.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgsUqoGj5-Lrlp-x9_bIh9U4atcNU7RwM',
    appId: '1:47237302350:ios:1904380180e8c854c71b1f',
    messagingSenderId: '47237302350',
    projectId: 'insync-class',
    storageBucket: 'insync-class.appspot.com',
    iosBundleId: 'com.example.insync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgsUqoGj5-Lrlp-x9_bIh9U4atcNU7RwM',
    appId: '1:47237302350:ios:1904380180e8c854c71b1f',
    messagingSenderId: '47237302350',
    projectId: 'insync-class',
    storageBucket: 'insync-class.appspot.com',
    iosBundleId: 'com.example.insync',
  );
}
